### ISSUE TITLE
Rouli font not found 

### ISSUE THREAD

**Issue by PaulEvans8669** [Rouli-M/GordonWare#1]
Erreur quand l'utilisateur n'a pas la font "Rouli" sur son PC.

> /GordonWare/Content/Rouli.spritefont : error : Processor 'FontDescriptionProcessor' had unexpected failure!
1>  System.IO.FileNotFoundException: Could not find "Rouli" font file.
1>     à Microsoft.Xna.Framework.Content.Pipeline.Processors.FontDescriptionProcessor.Process(FontDescription input, ContentProcessorContext context)
1>     à Microsoft.Xna.Framework.Content.Pipeline.ContentProcessor`2.Microsoft.Xna.Framework.Content.Pipeline.IContentProcessor.Process(Object input, ContentProcessorContext context)
1>     à MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.ProcessContent(PipelineBuildEvent pipelineEvent)
1>C:\Program Files (x86)\MSBuild\MonoGame\v3.0\MonoGame.Content.Builder.targets(84,5): error MSB3073: La commande ""C:\Program Files (x86)\MSBuild\MonoGame\v3.0\Tools\MGCB.exe" /quiet /platform:Windows /@:"C:\Users\\----\Desktop\GordonWare\Content\Content.mgcb" /outputDir:"bin\Windows\Content" /intermediateDir:"obj\Windows\Content"" s'est arrêtée avec le code 1.

Edit: L'erreur apparaît également après avoir installé Roulit5.ttf

**Comment by Rouli-M** [comment]
Tu peux me dire si ça marche depuis 47dc7ca ?

**Comment by PaulEvans8669** [comment]
L'erreur est réparée.
