### ISSUE TITLE
Need some documentation

### ISSUE THREAD

**Issue by SuperFola** [Rouli-M/GordonWare#5]
Because documentation is cool and that would be easier for newcomers to contribute

**Comment by Rouli-M** [comment]
It's planned! :)

**Comment by Rouli-M** [comment]
Documentation was added in [the wiki](https://github.com/Rouli-M/GordonWare/wiki/What-is-Gordon-Ware-and-how-to-contribute) for global context, but also in the code in the form of commentary.
